import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import FontProvider from "@/context/font-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Providers>
          <FontProvider>{children}</FontProvider>
        </Providers>
      </body>
    </html>
  );
}
